2missing details README.md
drknzz/GitHub-Achievements pull request #113
Opened 2023-06-09 19:37 UTC by venom-mancer

Updated README.md for 2 new achivements (**Open Sourcerer**) & (**Heart On Your Sleeve**)

2023-06-22 17:30 UTC, frannet82 requested changes
Please resolve conflicts

2023-06-24 10:29 UTC, venom-mancer commented
Conflicts fixed and ready to go , But check it before you aprove it my friend

2023-08-23 04:49 UTC, ashishkumar30 approved these changes

2023-09-04 22:45 UTC, frannet82 approved these changes

2025-10-18 21:05 UTC, closed without merging

2026-02-08 18:36 UTC, ahmedIdrissDev commented
When do developers hate bugs the most? When their coffee runs out

2026-09-29 07:38 UTC, Hackernaina commented
please improvise formatting