A symbol changed
drknzz/GitHub-Achievements pull request #28
Opened 2022-11-24 06:40 UTC by NathanBollard

Just a small one for more pull sharks

2022-11-29 01:34 UTC, gianlucajahn commented
kinda sus

2022-11-29 05:46 UTC, NathanBollard commented
This has been open for almost a week now. Can it be merged yet?

2022-11-30 18:45 UTC, matthewholt1 commented
Big thank you to this guy for opening a PR for a single character.

2022-12-15 12:23 UTC, Wrongtown requested changes
This change is unnecessary. The `(c)` is widely recognised and though unicode _is_ widely accepted, parentheses are even _more_ widely accepted 🤷‍♂️ 

Doesn't look like the repo owner is interested in merging this change mate; I suggest you should close the PR.

2023-01-02 18:49 UTC, Johnmiicheal reviewed
😂😂

2023-01-10 14:40 UTC, port19x requested changes

2023-01-10 14:40 UTC, port19x commented on LICENSE
> +Copyright © 2022 Kamil Jankowski
:moyai:

2023-01-10 16:03 UTC, kurbus commented
Okay guys this one has run its course can we close this now

2023-01-13 13:19 UTC, MitkoVtori requested changes
This change is unnecessary. It might look good, but it doesn't really matter. It's been a while though, @drknzz would you close it or merge it?

2023-01-13 13:20 UTC, closed without merging